jwt:
  access-token-expiration-millis: 600000
  secret-key: MGRmYjU5ZDMtNTJkMi00OTM2LTkzOTgtZjM0YmFhZTVhOGFl

spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: 'jdbc:h2:mem:testdb'
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true
